name: Folk Live-Build

on:
  workflow_dispatch:   # allows you to manually trigger the build
  push:
    branches:
      - main

jobs:
  build:
    name: Build Folk Live Image
    runs-on: ubuntu-22.04

    permissions:
      contents: read

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Step 2: Install dependencies
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            build-essential \
            live-build \
            debootstrap \
            systemd-container \
            squashfs-tools \
            xorriso \
            genisoimage \
            parted \
            dosfstools \
            zip \
            sudo \
            procps \
            uidmap \
            fakeroot \
            eatmydata

      # Step 3: Build apriltag library (solid part)
      - name: Build apriltag
        run: |
          cd folk/live-build/config/includes.chroot_after_packages/home/folk/apriltag
          make libapriltag.a libapriltag.so

      # Step 4: Prepare output directory
      - name: Setup output directory
        run: mkdir -p $GITHUB_WORKSPACE/output

      # Step 5: Run live-build
      - name: Run live-build
        run: |
          cd folk/live-build
          lb clean
          lb config
          sudo lb bootstrap
          sudo lb build
          
      # Step 6: Upload the artifacts
      - name: Upload built images
        uses: actions/upload-artifact@v4
        with:
          name: folk-live-build
          path: |
            folk/live-build/live-image-*
            folk/live-build/binary*

- name: Cache apt packages
  uses: actions/cache@v4
  with:
    path: /var/cache/apt
    key: ${{ runner.os }}-apt-${{ hashFiles('**/Dockerfile') }}
    restore-keys: |
      ${{ runner.os }}-apt-

